
FROM python:3.13

WORKDIR /app
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt
COPY ./app /app
RUN chown -R 1000:1000 /app
RUN git config --global --add safe.directory /app

CMD ["fastapi", "run", "app/main.py", "--port", "80"]


